# Generated by Django 5.2.4 on 2025-08-15 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whatsappsubscriber',
            name='consent',
        ),
        migrations.RemoveField(
            model_name='whatsappsubscriber',
            name='is_active',
        ),
    ]
