# Generated by Django 5.2.4 on 2025-07-29 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0002_sellerprofile_delete_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='category',
            field=models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('kids', 'Kids'), ('accessories', 'Accessories'), ('beauty', 'Beauty')], default='men', max_length=20),
        ),
    ]
