# Generated by Django 5.2.4 on 2025-08-14 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0002_alter_sellerprofile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
