# Generated by Django 5.2.4 on 2025-08-17 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_original_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('men_shirts', 'Shirts'), ('men_tshirts', 'T-Shirts'), ('men_pants', 'Pants'), ('men_jeans', 'Jeans'), ('men_shorts', 'Shorts'), ('men_jackets', 'Jackets'), ('men_shoes', 'Shoes'), ('men_accessories', 'Accessories'), ('women_tops', 'Tops'), ('women_dresses', 'Dresses'), ('women_pants', 'Pants'), ('women_jeans', 'Jeans'), ('women_skirts', 'Skirts'), ('women_jackets', 'Jackets'), ('women_shoes', 'Shoes'), ('women_bags', 'Bags'), ('women_jewelry', 'Jewelry'), ('kids_boys_clothing', 'Boys Clothing'), ('kids_girls_clothing', 'Girls Clothing'), ('kids_shoes', 'Kids Shoes'), ('kids_toys', 'Toys'), ('kids_accessories', 'Kids Accessories'), ('accessories_bags', 'Bags'), ('accessories_jewelry', 'Jewelry'), ('accessories_watches', 'Watches'), ('accessories_sunglasses', 'Sunglasses'), ('accessories_belts', 'Belts'), ('accessories_hats', 'Hats'), ('beauty_skincare', 'Skincare'), ('beauty_makeup', 'Makeup'), ('beauty_haircare', 'Hair Care'), ('beauty_fragrances', 'Fragrances'), ('beauty_tools', 'Beauty Tools')], help_text='Product subcategory', max_length=50, null=True),
        ),
    ]
